version: "3.9"

networks:
  hw2:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_hw2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '${DB_HOST}:5432:5432'
    networks:
      - hw2
  grpc-server:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/grpc_server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - hw2
  grpc-gateway:
    restart: always
    depends_on:
      - grpc-server
    build:
      context: .
      dockerfile: docker/grpc_gateway/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - hw2