// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/v1/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SomeStuffClient is the client API for SomeStuff service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SomeStuffClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskID, error)
	CreateTaskStage(ctx context.Context, in *CreateTaskStageRequest, opts ...grpc.CallOption) (*TaskStageID, error)
	GetTasksList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TasksList, error)
	SubscribeUser(ctx context.Context, in *SubscribeUserRequest, opts ...grpc.CallOption) (*SubscribeUserResponse, error)
	UnsubscribeUser(ctx context.Context, in *UnsubscribeUserRequest, opts ...grpc.CallOption) (*UnsubscribeUserResponse, error)
	GetUserTasksByTime(ctx context.Context, in *GetUserTasksByTimeRequest, opts ...grpc.CallOption) (*TasksList, error)
}

type someStuffClient struct {
	cc grpc.ClientConnInterface
}

func NewSomeStuffClient(cc grpc.ClientConnInterface) SomeStuffClient {
	return &someStuffClient{cc}
}

func (c *someStuffClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/SomeStuff/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someStuffClient) CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskID, error) {
	out := new(TaskID)
	err := c.cc.Invoke(ctx, "/SomeStuff/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someStuffClient) CreateTaskStage(ctx context.Context, in *CreateTaskStageRequest, opts ...grpc.CallOption) (*TaskStageID, error) {
	out := new(TaskStageID)
	err := c.cc.Invoke(ctx, "/SomeStuff/CreateTaskStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someStuffClient) GetTasksList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TasksList, error) {
	out := new(TasksList)
	err := c.cc.Invoke(ctx, "/SomeStuff/GetTasksList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someStuffClient) SubscribeUser(ctx context.Context, in *SubscribeUserRequest, opts ...grpc.CallOption) (*SubscribeUserResponse, error) {
	out := new(SubscribeUserResponse)
	err := c.cc.Invoke(ctx, "/SomeStuff/SubscribeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someStuffClient) UnsubscribeUser(ctx context.Context, in *UnsubscribeUserRequest, opts ...grpc.CallOption) (*UnsubscribeUserResponse, error) {
	out := new(UnsubscribeUserResponse)
	err := c.cc.Invoke(ctx, "/SomeStuff/UnsubscribeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someStuffClient) GetUserTasksByTime(ctx context.Context, in *GetUserTasksByTimeRequest, opts ...grpc.CallOption) (*TasksList, error) {
	out := new(TasksList)
	err := c.cc.Invoke(ctx, "/SomeStuff/GetUserTasksByTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SomeStuffServer is the server API for SomeStuff service.
// All implementations must embed UnimplementedSomeStuffServer
// for forward compatibility
type SomeStuffServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	CreateTask(context.Context, *Task) (*TaskID, error)
	CreateTaskStage(context.Context, *CreateTaskStageRequest) (*TaskStageID, error)
	GetTasksList(context.Context, *emptypb.Empty) (*TasksList, error)
	SubscribeUser(context.Context, *SubscribeUserRequest) (*SubscribeUserResponse, error)
	UnsubscribeUser(context.Context, *UnsubscribeUserRequest) (*UnsubscribeUserResponse, error)
	GetUserTasksByTime(context.Context, *GetUserTasksByTimeRequest) (*TasksList, error)
	mustEmbedUnimplementedSomeStuffServer()
}

// UnimplementedSomeStuffServer must be embedded to have forward compatible implementations.
type UnimplementedSomeStuffServer struct {
}

func (UnimplementedSomeStuffServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSomeStuffServer) CreateTask(context.Context, *Task) (*TaskID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedSomeStuffServer) CreateTaskStage(context.Context, *CreateTaskStageRequest) (*TaskStageID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTaskStage not implemented")
}
func (UnimplementedSomeStuffServer) GetTasksList(context.Context, *emptypb.Empty) (*TasksList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasksList not implemented")
}
func (UnimplementedSomeStuffServer) SubscribeUser(context.Context, *SubscribeUserRequest) (*SubscribeUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeUser not implemented")
}
func (UnimplementedSomeStuffServer) UnsubscribeUser(context.Context, *UnsubscribeUserRequest) (*UnsubscribeUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsubscribeUser not implemented")
}
func (UnimplementedSomeStuffServer) GetUserTasksByTime(context.Context, *GetUserTasksByTimeRequest) (*TasksList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTasksByTime not implemented")
}
func (UnimplementedSomeStuffServer) mustEmbedUnimplementedSomeStuffServer() {}

// UnsafeSomeStuffServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SomeStuffServer will
// result in compilation errors.
type UnsafeSomeStuffServer interface {
	mustEmbedUnimplementedSomeStuffServer()
}

func RegisterSomeStuffServer(s grpc.ServiceRegistrar, srv SomeStuffServer) {
	s.RegisterService(&SomeStuff_ServiceDesc, srv)
}

func _SomeStuff_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeStuffServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomeStuff/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeStuffServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeStuff_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeStuffServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomeStuff/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeStuffServer).CreateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeStuff_CreateTaskStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeStuffServer).CreateTaskStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomeStuff/CreateTaskStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeStuffServer).CreateTaskStage(ctx, req.(*CreateTaskStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeStuff_GetTasksList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeStuffServer).GetTasksList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomeStuff/GetTasksList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeStuffServer).GetTasksList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeStuff_SubscribeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeStuffServer).SubscribeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomeStuff/SubscribeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeStuffServer).SubscribeUser(ctx, req.(*SubscribeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeStuff_UnsubscribeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeStuffServer).UnsubscribeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomeStuff/UnsubscribeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeStuffServer).UnsubscribeUser(ctx, req.(*UnsubscribeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeStuff_GetUserTasksByTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTasksByTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeStuffServer).GetUserTasksByTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomeStuff/GetUserTasksByTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeStuffServer).GetUserTasksByTime(ctx, req.(*GetUserTasksByTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SomeStuff_ServiceDesc is the grpc.ServiceDesc for SomeStuff service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SomeStuff_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SomeStuff",
	HandlerType: (*SomeStuffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _SomeStuff_CreateUser_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _SomeStuff_CreateTask_Handler,
		},
		{
			MethodName: "CreateTaskStage",
			Handler:    _SomeStuff_CreateTaskStage_Handler,
		},
		{
			MethodName: "GetTasksList",
			Handler:    _SomeStuff_GetTasksList_Handler,
		},
		{
			MethodName: "SubscribeUser",
			Handler:    _SomeStuff_SubscribeUser_Handler,
		},
		{
			MethodName: "UnsubscribeUser",
			Handler:    _SomeStuff_UnsubscribeUser_Handler,
		},
		{
			MethodName: "GetUserTasksByTime",
			Handler:    _SomeStuff_GetUserTasksByTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/api.proto",
}
